name: goim.service.user
version: v0.0.0
grpc:
  scheme: grpc
  port: 18053
  timeout: 5s
log:
  level: DEBUG
  enable_console: true
  log_path: ./logs
metadata:
  grpcSrv: yes
redis:
  addr: 127.0.0.1:6379
mysql:
  addr: 127.0.0.1:3306
  user: root
  password: goim123456
  db: goim
  max_open_conns: 1000
# services name
gatewayService: service.goim.gateway
userService: service.goim.user
pushService: service.goim.push
storeService: service.goim.store
msgService: service.goim.msg